config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'bloom_beauty/home'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :orders
  resources :products
  resources :product_categories
  resources :customers
  resources :suppliers
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'bloom_beauty#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :orders
	validates_presence_of :name, :address, :phone
	validates_numericality_of :phone
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :address, :phone, :email)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p>
    <strong>Name:</strong>
    <%= customer.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= customer.address %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= customer.phone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= customer.email %>
  </p>

</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer) do |form| %>
<% if customer.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% customer.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :name, class: label_class %>
          <%= form.text_field :name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :address, class: label_class %>
          <%= form.text_field :address, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :phone, class: label_class %>
          <%= form.text_field :phone, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :email, class: label_class %>
          <%= form.text_field :email, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if customer.persisted? %>
<%= link_to "Cancel", customer, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", customers_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/customers/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit customer</h1>
    <% if @customer.persisted? %>
    <%= button_to 'Destroy', @customer, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', customer: @customer %>
</div>

app/views/customers/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Customers</h1>

    <%= link_to new_customer_path, class: button_class(theme: "primary") do %>
    Add New Customer
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Address</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Phone</th>
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Email</th>
                
      </tr>
    </thead>

    <tbody>
      <% @customers.each do |customer| %>
      <%= content_tag :tr, id: dom_id(customer), class: dom_class(customer) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to customer.name, customer %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= customer.address %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= customer.phone %></td>
              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= customer.email %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/customers/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New customer</h1>

  <%= render 'form', customer: @customer %>
</div>

app/views/customers/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Customer</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to customers_path, class: button_class(theme: "transparent") do %>
      All Customers
      <% end %>
      <%= link_to edit_customer_path(@customer), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Name:</p>
        <p><%= @customer.name %></p>
      </li>
      <li>
        <p class="font-semibold">Address:</p>
        <p><%= @customer.address %></p>
      </li>
      <li>
        <p class="font-semibold">Phone:</p>
        <p><%= @customer.phone %></p>
      </li>
      <li>
        <p class="font-semibold">Email:</p>
        <p><%= @customer.email %></p>
      </li>
  </ul>
</div>