config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'bloom_beauty/home'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :orders
  resources :products
  resources :product_categories
  resources :customers
  resources :suppliers
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end


  devise_for :users
  root to: 'bloom_beauty#home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
	has_many :products
	validates_presence_of :name, :description
	validates_uniqueness_of :name
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  before_action :set_product_category, only: %i[ show edit update destroy ]

  # GET /product_categories or /product_categories.json
  def index
    @product_categories = ProductCategory.all
  end

  # GET /product_categories/1 or /product_categories/1.json
  def show
  end

  # GET /product_categories/new
  def new
    @product_category = ProductCategory.new
  end

  # GET /product_categories/1/edit
  def edit
  end

  # POST /product_categories or /product_categories.json
  def create
    @product_category = ProductCategory.new(product_category_params)

    respond_to do |format|
      if @product_category.save
        format.html { redirect_to product_category_url(@product_category), notice: "Product category was successfully created." }
        format.json { render :show, status: :created, location: @product_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_categories/1 or /product_categories/1.json
  def update
    respond_to do |format|
      if @product_category.update(product_category_params)
        format.html { redirect_to product_category_url(@product_category), notice: "Product category was successfully updated." }
        format.json { render :show, status: :ok, location: @product_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_categories/1 or /product_categories/1.json
  def destroy
    @product_category.destroy

    respond_to do |format|
      format.html { redirect_to product_categories_url, notice: "Product category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_category
      @product_category = ProductCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_category_params
      params.require(:product_category).permit(:name, :description)
    end
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/views/product_categories/_form.html.erb
<%= form_with(model: product_category) do |form| %>
<% if product_category.errors.any? %>
<div id="error_explanation" class="bg-red-50 p-6 rounded text-red-800">
  <h2 class="text-lg font-semibold mb-3"><%= pluralize(product_category.errors.count, "error") %> prohibited this product_category from being saved:</h2>

  <ul class="list-disc leading-relaxed">
    <% product_category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

  <div class="mb-6">
        <%= form.label :name, class: label_class %>
          <%= form.text_field :name, class: input_class %>
      </div>
  <div class="mb-6">
        <%= form.label :description, class: label_class %>
          <%= form.text_area :description, class: input_class %>
      </div>

<%= form.submit class: button_class(theme: 'primary') %>

<% if product_category.persisted? %>
<%= link_to "Cancel", product_category, class: "text-neutral-700 underline inline-block ml-3" %>
<% else %>
<%= link_to "Cancel", product_categories_path, class:  "text-neutral-700 underline inline-block ml-3" %>
<% end %>
<% end %>

app/views/product_categories/_product_category.html.erb
<div id="<%= dom_id product_category %>">
  <p>
    <strong>Name:</strong>
    <%= product_category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product_category.description %>
  </p>

</div>

app/views/product_categories/edit.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between mb-6 flex-wrap">
    <h1 class="font-bold text-3xl mb-6">Edit product_category</h1>
    <% if @product_category.persisted? %>
    <%= button_to 'Destroy', @product_category, method: :delete, class: "text-red-700 underline", data: { turbo_confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <%= render 'form', product_category: @product_category %>
</div>

app/views/product_categories/index.html.erb
<div class="container mx-auto px-4">
  <div class="flex items-center justify-between flex-wrap mb-6">
    <h1 class="text-3xl font-bold">Product_categories</h1>

    <%= link_to new_product_category_path, class: button_class(theme: "primary") do %>
    Add New Product category
    <% end %>
  </div>

  <table class="table-auto border-collapse border-slate-400 w-full">
    <thead class="bg-slate-50 dark:bg-slate-700">
      <tr>
        
          <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Name</th>
        
                  <th class="border border-slate-300 dark:border-slate-600 font-semibold p-4 text-slate-900 dark:text-slate-200 text-left">Description</th>
                
      </tr>
    </thead>

    <tbody>
      <% @product_categories.each do |product_category| %>
      <%= content_tag :tr, id: dom_id(product_category), class: dom_class(product_category) do %>
      
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= link_to product_category.name, product_category %></td>
      

              <td class="border border-slate-300 dark:border-slate-700 p-4 text-slate-500 dark:text-slate-400"><%= product_category.description %></td>
      
      
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/product_categories/new.html.erb
<div class="max-w-3xl mx-auto px-4">
  <h1 class="font-bold text-3xl mb-6">New product_category</h1>

  <%= render 'form', product_category: @product_category %>
</div>

app/views/product_categories/show.html.erb
<div class="max-w-3xl mx-auto px-4">
  <div class="flex items-center justify-between">
    <h1 class="flex-1 font-bold text-3xl">Product_category</h1>

    <div class="flex-wrap lg:flex items-center lg:space-x-3">
      <%= link_to product_categories_path, class: button_class(theme: "transparent") do %>
      All Product_categories
      <% end %>
      <%= link_to edit_product_category_path(@product_category), class: button_class(theme:"primary") do %>
      Edit
      <% end %>
    </div>
  </div>

  <ul class="text-slate-700">
      <li>
        <p class="font-semibold">Name:</p>
        <p><%= @product_category.name %></p>
      </li>
      <li>
        <p class="font-semibold">Description:</p>
        <p><%= @product_category.description %></p>
      </li>
  </ul>
</div>